name: release

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    # Run at 4PM UTC every Monday
    - cron: '0 16 * * 1'

jobs:
  alpine-316:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - name: Build
        run: |
          docker buildx build \
            --push \
            --platform linux/arm64,linux/amd64 \
            --build-arg OS_NAME="alpine" \
            --build-arg OS_VERSION="3.16" \
            -f alpine.Dockerfile \
            -t truemark/aws-cli:2-${{github.run_number}}-alpine-3.16 \
            -t truemark/aws-cli:2-alpine-3.16 \
            -t truemark/aws-cli:alpine-3.16 \
            .
  alpine-317:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - name: Build
        run: |
          docker buildx build \
            --push \
            --platform linux/arm64,linux/amd64 \
            --build-arg OS_NAME="alpine" \
            --build-arg OS_VERSION="3.17" \
            -f alpine.Dockerfile \
            -t truemark/aws-cli:2-${{github.run_number}}-alpine-3.17 \
            -t truemark/aws-cli:2-alpine-3.17 \
            -t truemark/aws-cli:alpine-3.17 \
            -t truemark/aws-cli:alpine \
            .
  ubuntu-focal:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - name: Build
        run: |
          docker buildx build \
            --push \
            --platform linux/arm64,linux/amd64 \
            --build-arg OS_NAME="ubuntu" \
            --build-arg OS_VERSION="focal" \
            -f Dockerfile \
            -t truemark/aws-cli:2-${{github.run_number}}-ubuntu-focal \
            -t truemark/aws-cli:2-ubuntu-focal \
            -t truemark/aws-cli:ubuntu-focal \
            .
  ubuntu-jammy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - name: Build
        run: |
          docker buildx build \
            --push \
            --platform linux/arm64,linux/amd64 \
            --build-arg OS_NAME="ubuntu" \
            --build-arg OS_VERSION="jammy" \
            -f Dockerfile \
            -t truemark/aws-cli:2-${{github.run_number}}-ubuntu-jammy \
            -t truemark/aws-cli:2-ubuntu-jammy \
            -t truemark/aws-cli:ubuntu-jammy \
            -t truemark/aws-cli:ubuntu \
            .
  debian-buster:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - name: Build
        run: |
          docker buildx build \
            --push \
            --platform linux/arm64,linux/amd64 \
            --build-arg OS_NAME="debian" \
            --build-arg OS_VERSION="buster" \
            -f Dockerfile \
            -t truemark/aws-cli:2-${{github.run_number}}-debian-buster \
            -t truemark/aws-cli:2-debian-buster \
            -t truemark/aws-cli:debian-buster \
            .
  debian-bullseye:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - name: Build
        run: |
          docker buildx build \
            --push \
            --platform linux/arm64,linux/amd64 \
            --build-arg OS_NAME="debian" \
            --build-arg OS_VERSION="bullseye" \
            -f Dockerfile \
            -t truemark/aws-cli:2-${{github.run_number}}-debian-bullseye \
            -t truemark/aws-cli:2-debian-bullseye \
            -t truemark/aws-cli:debian-bullseye \
            .
  debian-bookworm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - name: Build
        run: |
          docker buildx build \
            --push \
            --platform linux/arm64,linux/amd64 \
            --build-arg OS_NAME="debian" \
            --build-arg OS_VERSION="bookworm" \
            -f Dockerfile \
            -t truemark/aws-cli:2-${{github.run_number}}-debian-bookworm \
            -t truemark/aws-cli:2-debian-bookworm \
            -t truemark/aws-cli:debian-bookworm \
            -t truemark/aws-cli:debian \
            .
  debian-buster-slim:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - name: Build
        run: |
          docker buildx build \
            --push \
            --platform linux/arm64,linux/amd64 \
            --build-arg OS_NAME="debian" \
            --build-arg OS_VERSION="buster-slim" \
            -f Dockerfile \
            -t truemark/aws-cli:2-${{github.run_number}}-debian-buster-slim \
            -t truemark/aws-cli:2-debian-buster-slim \
            -t truemark/aws-cli:debian-buster-slim \
            .
  debian-bullseye-slim:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - name: Build
        run: |
          docker buildx build \
            --push \
            --platform linux/arm64,linux/amd64 \
            --build-arg OS_NAME="debian" \
            --build-arg OS_VERSION="bullseye-slim" \
            -f Dockerfile \
            -t truemark/aws-cli:2-${{github.run_number}}-debian-bullseye-slim \
            -t truemark/aws-cli:2-debian-bullseye-slim \
            -t truemark/aws-cli:debian-bullseye-slim \
            .
  debian-bookworm-slim:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - name: Build
        run: |
          docker buildx build \
            --push \
            --platform linux/arm64,linux/amd64 \
            --build-arg OS_NAME="debian" \
            --build-arg OS_VERSION="bullseye-slim" \
            -f Dockerfile \
            -t truemark/aws-cli:2-${{github.run_number}}-debian-bookworm-slim \
            -t truemark/aws-cli:2-debian-bookworm-slim \
            -t truemark/aws-cli:debian-bookworm-slim \
            .
  amazonlinux-2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - name: Build
        run: |
          docker buildx build \
            --push \
            --platform linux/arm64,linux/amd64 \
            --build-arg OS_NAME="amazonlinux" \
            --build-arg OS_VERSION="2" \
            -f Dockerfile \
            -t truemark/aws-cli:2-${{github.run_number}}-amazonlinux-2 \
            -t truemark/aws-cli:2-amazonlinux-2 \
            -t truemark/aws-cli:amazonlinux-2 \
            .
  amazonlinux-2022:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - name: Build
        run: |
          docker buildx build \
            --push \
            --platform linux/arm64,linux/amd64 \
            --build-arg OS_NAME="amazonlinux" \
            --build-arg OS_VERSION="2022" \
            -f Dockerfile \
            -t truemark/aws-cli:2-${{github.run_number}}-amazonlinux-2022 \
            -t truemark/aws-cli:2-amazonlinux-2022 \
            -t truemark/aws-cli:amazonlinux-2022 \
            -t truemark/aws-cli:amazonlinux \
            .
      - name: Keepalive
        uses: gautamkrishnar/keepalive-workflow@v1
