name: release

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    # Run at 4PM UTC every Monday
    - cron: '0 16 * * 1'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - name: Build
        run: |
          docker buildx build \
            --push \
            --platform linux/arm64,linux/amd64 \
            -f amazonlinux2.Dockerfile \
            -t truemark/aws-cli:2-${{github.run_number}}-amazonlinux2 \
            -t truemark/aws-cli:2-amazonlinux2 \
            -t truemark/aws-cli:amazonlinux2 \
            .
          docker buildx build \
            --push \
            --platform linux/arm64,linux/amd64 \
            -f amazonlinux2022.Dockerfile \
            -t truemark/aws-cli:2-${{github.run_number}}-amazonlinux2022 \
            -t truemark/aws-cli:2-amazonlinux2022 \
            -t truemark/aws-cli:2 \
            -t truemark/aws-cli:amazonlinux2022 \
            -t truemark/aws-cli:latest \
            .
          docker buildx build \
            --push \
            --platform linux/arm64,linux/amd64 \
            -f ubuntu-focal.Dockerfile \
            -t truemark/aws-cli:2-${{github.run_number}}-ubuntu-focal \
            -t truemark/aws-cli:2-ubuntu-focal \
            -t truemark/aws-cli:ubuntu-focal \
            .
          docker buildx build \
            --push \
            --platform linux/arm64,linux/amd64 \
            -f ubuntu-jammy.Dockerfile \
            -t truemark/aws-cli:2-${{github.run_number}}-ubuntu-jammy \
            -t truemark/aws-cli:2-ubuntu-jammy \
            -t truemark/aws-cli:ubuntu-jammy \
            -t truemark/aws-cli:2-ubuntu \
            -t truemark/aws-cli:ubuntu \
            .
          docker buildx build \
            --push \
            --platform linux/arm64,linux/amd64 \
            -f alpine.Dockerfile \
            -t truemark/aws-cli:2-${{github.run_number}}-alpine \
            -t truemark/aws-cli:2-alpine \
            -t truemark/aws-cli:alpine \
            .
      - name: Keepalive
        uses: gautamkrishnar/keepalive-workflow@v1
